stages:
  Data_Preparation:
    cmd: python src/data/data_preparation.py
    params:
     - Data_Preparation.test_size
     - Data_Preparation.random_state

    deps:
      - data/raw/real_estatesv9.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  Data_Preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
     - data/interim/train.csv
     - data/interim/test.csv
     - src/data/data_preparation.py
    outs:
     - data/processed/train_trans.csv
     - data/processed/test_trans.csv

  