stages:
  Data_Preparation:
    cmd: python src/data/data_preparation.py
    params:
     - Data_Preparation.test_size
     - Data_Preparation.random_state

    deps:
      - data/raw/real_estatesv9.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  Data_Preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
     - data/interim/train.csv
     - data/interim/test.csv
     - src/data/data_preparation.py
    outs:
     - data/processed/train_trans.csv
     - data/processed/test_trans.csv
     - models/preprocesser.joblib

  Train:
    cmd: python src/models/train.py
    deps:
     - data/processed/train_trans.csv
     - models/preprocesser.joblib
     - src/models/train.py
    params:
     - Train.Random_Forest
     - Train.LightGBM
    outs:
     - models/model.joblib
     - models/stacking_regressor.joblib
     - models/log_transformer.joblib 